---
- name: Read current time zone
  shell: cat /etc/timezone
  changed_when: false
  register: current_time_zone

- name: Set the time zone
  shell: timedatectl set-timezone '{{ desired_time_zone }}'
  when: current_time_zone.stdout != desired_time_zone
